[build]
  command = "npm run build"
  publish = "public"

[functions]
  included_files = ["eng.traineddata", "eng.traineddata.gz"]
  external_node_modules = [
    "@tensorflow/tfjs",
    "upscaler",
    "@upscalerjs/default-model",
    "playwright-core"
  ]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
